language: python
python:
  - "2.7"
  - "3.3"
env:
  - DJANGO_VERSION=1.5.0
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.3.7
install:
  - pip install --use-mirrors -q Django==$DJANGO_VERSION && python setup.py -q install
script: tests/test.sh
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=1.4.5
    - python: "3.3"
      env: DJANGO_VERSION=1.3.7
